<?php

$console=(PHP_SAPI=='cli');

if ($console) {
    define('ROOT',substr($_SERVER['PHP_SELF'],0,-13).'../');
    require_once(ROOT.'classes/db.php');
} else {
    echo "Run this script from console!!";
    exit();
    define('ROOT','../');
    require_once(ROOT.'classes/init.php');
    require_once(ROOT.'classes/html.php');
    require_once(ROOT.'classes/user.php');

    $user->require_admin();

    HTML::header();
}

$fver= array();

function process_files($glob) {
    global $fver;
    foreach (glob(ROOT . $glob) as $file) {
        $fver[substr($file, strlen(ROOT))] = filemtime($file);
    }
}

process_files('js/*.js');
process_files('js/*/*.js');
process_files('css/*.css');
process_files('templates/*/*.js');

$f = fopen(ROOT.'config.auto.php','w');
function w($s='') { global $f; fwrite($f,$s."\n"); }
function warray($name, $val) {
    w('  ' . $name . ' = array(');
    foreach ($val as $k => $v)
        w('    \''.$k.'\' => \''.$v.'\',');
    w('  );');
    w();
}

w('<?php');
w('  // This file is autogenerated, do not modify!');
w();
w('
  class Config {
    public static $files_versions;
  };');
warray('Config::$files_versions', $fver);
w('?>');
fclose($f);

$scfg = file_get_contents(ROOT.'config.auto.php');

if ($console) {
    echo "config.auto.php created\n";
    // echo $scfg;
} else {
    $scfg = htmlentities($scfg);
    $scfg = str_replace("\n",'<br/>',$scfg);
    HTML::write('config.auto.php created:<br/><pre><code>'.$scfg.'</code></pre>');

    HTML::footer();
    HTML::flush();
}
?>
