<?php
  // This file is autogenerated, do not modify!


  class Config {
    public static $files_versions;
  };
  Config::$files_versions = array(
    'js/jquery-1.9.1.js' => '1403178304',
    'js/jquery-1.9.1.min.js' => '1403178304',
    'js/jquery-migrate-1.1.0.min.js' => '1403178304',
    'js/jquery-ui-1.10.1.custom.js' => '1403178304',
    'js/jquery-ui-1.10.1.custom.min.js' => '1403178304',
    'js/jquery.ba-bbq.js' => '1403178304',
    'js/jquery.form.js' => '1403178304',
    'js/jquery.ui.datepicker-ru.js' => '1403178304',
    'js/jquery.uploadfile.js' => '1403178304',
    'js/jquery.uploadfile.min.js' => '1403178304',
    'css/all.css' => '1404411520',
    'css/uploadfile.css' => '1403178304',
  );

?>
